openedx/testeng-ci

jenkins/build.py, jenkins/deduper.py, jenkins/job.py, jenkins/tests/helpers.py, jenkins/tests/test_deduper.py, jenkins/tests/test_job.py, jenkins/tests/test_timeout.py, jenkins/timeout.py, test-requirements.txt
This defaults to False. If set to True, it will leave one build running for each unique last commit author for a PR.
@clytwynec
=> Add deduper option for one_per_author

jenkins/tests/test_workers.py, jenkins/workers.py
@benpatterson  This is a small fix for an issue where the number of master executors was being reported incorrectly.
=> accurately count number of master executors

jenkins/freestyle/get-sitespeed-report.sh
PERF-179
@benpatterson this is used by the [get-sitespeed-report](https://test-jenkins.testeng.edx.org/job/get-sitespeed-report/) jenkins job (currently only on test-jenkins, not build)
=> Add script for the sitespeed job on jenkins

jenkins/freestyle/get-sitespeed-report.sh
@benpatterson I realize you caught this in the original code review, and I answered you incorrectly. :(
This should now work by forcing you to have the envar set to [something](https://github.com/edx/testeng-ci/blob/672f3e910e7ba47a55136d6cee25165573bd034d/jenkins/freestyle/get-sitespeed-report.sh#L20) and then only if that string is "True" (os environment variables are always string type) will it pass the credentials through to the scripts.
=> Fix basic auth envar usage for sitespeed

jenkins/freestyle/get-sitespeed-report.sh
@benpatterson apologies for the churn. :(
This time I tested by running the get-sitespeed job against a sandbox both with basic auth turned on and turned off (first confirming the auth setting manually in each case).
=> Really fix basic auth envar usage for sitespeed

jenkins/flow/master/edx-platform-bok-choy-master.groovy
The subset job has been updated to include the ENV_VARS parameter.
That parameter is a comma-delimited set of environment variables that will be set using the [EnvInject Plugin](https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin). The parameter string is parsed and individual environment variables are set in the environment by using the groovy utility of that plugin.
Using this approach, the parent job (build flow job) can receive those parameters to pass down to the child jobs. 
This means we can set various important environment variables as needed for running bok-choy. The best example is setting the SELENIUM_BROWSER variable to something else, or likewise passing the new accessibility-related settings.
@clytwynec @jzoldak could you review? 
An example of this is [here for …
=> Add ENV_VARS to bok-choy build flow.

jenkins/freestyle/github-build-status.sh
@benpatterson 
The job does not use the script programmatically.
Just sticking it here so that it's under source control.
=> Add the script for posting github build status and deployments

jenkins/flow/master/edx-platform-bok-choy-master.groovy
This will allow us to use the ENV_VARS feature for custom jobs, without
having those jobs report out to github.
=> Ability to opt-out of sending github status.

release/create_candidate_pr.py, release/github_api.py, release/tests/test_github_api.py, release/tests/test_utils.py, release/utils.py
By using this API endpoint, we will only see the latest statuses
for a given commit. New documentation ref added as part of this
commit.
Add find-commit switch, which will not create a branch or a
pull request; it will only output the commit that will be used.
=> Ensure only latest statuses are used. Add find-commit helper switch.

jenkins/freestyle/get-sitespeed-report.sh
@benpatterson this is ready for review.
Results:
* [without a budget](https://build.testeng.edx.org/view/sitespeed/job/browser-profiling-sitespeed/134/)
* [with a budget](https://build.testeng.edx.org/view/sitespeed/job/browser-profiling-sitespeed/135/)
=> Fix the JUnit test result report for the sitespeed profiling job

mobile_app/checkout_build_repos.py, mobile_app/test/test_checkout_build_repos.py
There was a problem where the new local branch wouldn't actually be
checked out to the remote HEAD of that branch, since we set the tracking
branch after creating the branch, the local HEAD wouldn't be the same as
the remote HEAD.
=> Fix issue checking out correct revision

release/create_candidate_pr.py
The old code wouldn't accept a date as advertised:
```
$ python -m release.create_candidate_pr --org edx --repo edx-platform --release-date 2016-03-03
2016-02-26 14:42:23,644 [INFO] Getting GitHub token...
2016-02-26 14:42:23,644 [INFO] Read saved token
2016-02-26 14:42:23,891 [INFO] Authenticated nedbat
2016-02-26 14:42:23,891 [INFO] Fetching commits...
Traceback (most recent call last):
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/src/edx/src/testeng-ci/release/create_candidate_pr.py", line 134, in <module> …
```
=> Fix the date argument handling

jenkins/freestyle/lms-budget-regression.json
This also enforces some additional items that are below the default score of 77.
=> Update sitespeed budget to reflect current state.

jenkins/sitespeed-budget/lms-budget-regression.json
This pull request includes more synchronous loading of javascript; however,
pages were not navigable before this resource loaded. From the perspective
of when the page is *usable*, this is a performance improvement. Adjusting
the budget in order to make the tests viable again.
=> Adjusting budget after platform PR 12266.

jenkins/build.py, jenkins/deduper.py, jenkins/job.py
Reverting edx/testeng-ci#61 because the deduper is now failing like this when run on Jenkins: 
```
00:00:05.265 Checking for extra builds of edx-platform-bok-choy-pr job...
00:00:05.305 Traceback (most recent call last):
00:00:05.305   File "jenkins/deduper.py", line 13, in <module>
00:00:05.306     from jenkins.job import JenkinsJob
00:00:05.306 ImportError: No module named jenkins.job
00:00:05.334 Build step 'Execute shell' marked build as failure
```
We don't really need to back out all the changes, but want to get the deduper back in action as quickly as possible as Jenkins is under water at the moment.
=> Revert "Pylint fixes for jenkins.build, .job, and .deduper"

jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
@benpatterson @estute @jzoldak 
I changed 2 parts of the script to be more flexible to different testing situations. 
1) Instead of hardcoding the edx-platform-test-subset into the script, it receives it as an environment variable that is injected by the bok-choy-pr job. However, it does default to edx-platform-test-subset
2) Instead of hardcoding that the files are copied to the edx-platform directory, it also receives this as an environment variable that is injected by the bok-choy-pr job. It defaults to edx-platform. 
The PR to accordingly modify bok-choy-pr job is https://github.com/edx/jenkins-job-dsl/pull/19
=> Modify Bokchoy Shard Script

jenkins/flow/master/edx-platform-bok-choy-master.groovy, jenkins/flow/master/edx-platform-lettuce-master.groovy, jenkins/flow/master/edx-platform-python-unittests-master.groovy
@benpatterson @jzoldak @estute 
This goes along with https://github.com/edx/jenkins-job-dsl/pull/21.
The changes made were to call the appropriate test-subset job rather than hard coding one subset  job and to copy a repo specific directory
=> Refactor for ReDeployment

mobile_app/test/test_trigger_build.py
@aphanse @estute please review.
This test was leaving confusing output on the console when the test was run.
Reproduce with: `nosetests -v mobile_app/test/test_trigger_build.py:TriggerBuildTestCase.test_missing_arguments`
Output prior to this change:
```
Tests that the command quits when not given ... usage: nosetests [-h] --branch-name [BRANCH_NAME] --trigger-repo-path
[TRIGGER_REPO_PATH]
nosetests: error: argument --branch-name is required
ok
----------------------------------------------------------------------
Ran 1 test in 0.069s
```
Output after this change:
```
Tests that the command quits when not given ... ok
----------------------------------------------------------------------
Ran 1 test in 0.071s
```
=> Patch stderr in test_missing_arguments

release/create_candidate_pr.py, release/github_api.py, release/tests/test_github_api.py
@doctoryes @benpatterson PTAL. 
This updates the RC creation script to:
- Delete and recreate the release-candidate branch for every release
- make the PR go to: release...release-candidate.
This goes in line with my updating of the release master documentation to use gocd that I am currently working.
=> GoCD modifications to the create PR script

jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
Previous merge included this param, which is not used by PR jobs.
=> Remove param that's only used in master jobs.

lambdas/webhook_forwarder/webhook_forwarder.py
rather than return the error in a json response.
This is needed so that the success or failure response metrics can be tracked at the API gateway.
=> Webhook forwarder raises an error 

lambdas/webhook_forwarder/README.md, lambdas/webhook_processor/README.md
Used to be edx-testeng-lambda-webhook, now its edx-tools-lambda-webhook
=> Update s3 bucket name in README

lambdas/process_webhooks/process_webhooks.py, lambdas/process_webhooks/test/test_process_webhooks.py, lambdas/send_from_queue/send_from_queue.py
Removing support for a list of urls for the target. In the future, we are likely going to replace this with different stages for different jenkins instances.
=> Simplify Spigot target and bump POST timeouts

lambdas/process_webhooks/process_webhooks.py, lambdas/process_webhooks/test/test_process_webhooks.py
In the Spigot, determine the target url's endpoint based on its X-GitHub-Event header.
pull_request and issue_comments will go to ../ghprbhook/
pushes will go to ../github-webhook/
=> Programatically determine target endpoint

jenkins/flow/master/edx-platform-bok-choy-master.groovy, jenkins/flow/master/edx-platform-lettuce-master.groovy, jenkins/flow/master/edx-platform-python-unittests-master.groovy
This should fix the extra contexts that can be seen on the most recent merge to https://github.com/edx/edx-platform/commits/open-release/ginkgo.master
=> update ginkgo contexts

lambdas/process_webhooks/README.md, lambdas/process_webhooks/constants.py, lambdas/process_webhooks/process_webhooks.py, lambdas/process_webhooks/test/test_process_webhooks.py, lambdas/send_from_queue/send_from_queue.py, test-requirements.txt, travis/build_info.py, travis/tests/test_build_info.py
Overview
---
The proposed PR allows the Spigot to query the Jenkins REST API to ensure that all expected jobs are triggered by platform pull_request hooks.
- When the Spigot identifies a pull_request hook on platform, it queries the Jenkins API and finds all running or queued builds matching that sha. Based on that hooks target (master/ficus/ginkgo/etc), it is able to identify whether or not all the expected jobs have been triggered.
- If all the jobs have been triggered, Github receives a 200 and no further action is required.
- If some jobs are missing, the hook is sent to the SQS queue for future processing. Inside the hook, the Spigot stores all of the jobs that were successfully triggered. This prevents us from having to worry about jobs like js or quality (which are much shorter …
=> Query Jenkins API for Platform PRs

.pep8, .travis.yml, jenkins/build.py, jenkins/tests/helpers.py, jenkins/tests/test_timeout.py, test-requirements.txt
or at least they're no longer in the first element of the array.
Also:
* switching from nose to pytest
* relaxing pep8 to allow longer lines
=> Action parameters placement in the dict is not deterministic in Jenkins 2.0

jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
Recently python build sizes have increased a lot. In an effort to stop python builds from filling up Jenkins data olume, I have put in a fix to how we call pytest(see:  https://github.com/edx/edx-platform/pull/16401). 
Additionally, I realized that we were storing duplicate versions of report data. The build flow scripts were copying build artifacts from the subet job shards back into the artifacts directory of the build flow job itself (as a staging area) and then copying them into the workspace. The rationale for this is so that both the HTML publisher plugin and shining panda coverage plugin can access the report artifacts once they are in the workspace. This PR simply cleans up the report artifacts in the artifacts directory of the build flow job. Both aforementioned plugins store …
=> clean up python artifacts

jenkins/bokchoy_db_pull_request.py, jenkins/tests/test_bokchoy_db_pull_request.py, requirements.txt
This python script creates a PR into master with db cache file changes.
The plan is to have the python script run on every merge to master (after running the appropriate paver commands), and determine based on the files in the job's edx-platform workspace if there are changes that need to be committed. This seemed more logical than it being dependent on a paver task passing some sort of status/return value.
Note:
- It seems like theres no way to update/create a file without also creating a commit. So these PR's will have multiple commits. We could just select "squash and merge" when merging them in as somewhat of a solution.
=> Script for auto PR of bokchoy db cache updates

jenkins/bokchoy_db_pull_request.py
Should include the branch name when logging that a branch exists.
=> Fix log statement when branch exists for db cache uploader

jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
[TE-2385]
This pull request is part of a multi-pr change to disable both running unit tests through coverage and the coverage job for the django 1.11 upgrade work.
This pull request passes an environment variable for whether or not we should run coverage to the shards running the unit tests (see: 
https://github.com/edx/edx-platform/pull/17208) , and also conditionally calls the coverage job afterwards.
=> add env var to not run coverage on django jobs

jenkins/edx-platform-test-notifier.py
Python script to be run with the test notifier job. More here: https://github.com/edx/jenkins-job-dsl/pull/307
This script gets run at the end of an edx-platform PR build. It checks to see if there are any other pending contexts, and if there is not, posts a comment alerting the user that their tests have finished running.
=> Add test notifier python script

jenkins/edx-platform-test-notifier.py
This refactors the notification code a bit to make it more generic for any type of action on a PR, that can be taken given any kind of logic surrounding a PR.
The first addition to this is adding the ability to ignore the bot, e.g. through a line in the PR body.
To test this, open a PR on the edx-platform with `edx-status-bot: ignore` somewhere, run the job for this PR, and note that it'll ignore the PR. Then remove the line and re-run the job for that PR, and note that it does post something.
=> Add a generic EdxStatusBot class that can ignore PRs (and more).

jenkins/edx-platform-test-notifier.py
This bot is causing too much clutter on PR's. Deleting old messages before posting a new one alleviates this clutter and will hopefully get more people using this feature.
=> Remove old edx-status-bot messages from PR's

jenkins/flow/pr/edx-platform-bok-choy-pr.groovy, jenkins/flow/pr/edx-platform-lettuce-pr.groovy, jenkins/flow/pr/edx-platform-python-unittests-pr.groovy, jenkins/flow/pr/edx-platform-quality-pr.groovy
Following https://github.com/edx/edx-platform/pull/18377, this allows the tox environment variable to be passed from flow job to subset job. NOTE: this does not account for master jobs, which should be addressed in a separate ticket.
=> use toxEnv instead of djangoVersion

jenkins/edx_platform_test_notifier.py
I noticed a fair amount of notifier jobs failing recently. Here is the error msg:
```
00:00:03.082 Running test notifier script...
00:00:03.708 Traceback (most recent call last):
00:00:03.708   File "jenkins/edx_platform_test_notifier.py", line 160, in <module>
00:00:03.708     main()
00:00:03.708   File "/home/jenkins/workspace/edx-platform-test-notifier/test_notifier_venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
00:00:03.709     return self.main(*args, **kwargs)
00:00:03.709   File "/home/jenkins/workspace/edx-platform-test-notifier/test_notifier_venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
00:00:03.709     rv = self.invoke(ctx)
00:00:03.709   File "/home/jenkins/workspace/edx-platform-test-notifier/test_notifier_venv/local/lib/p …
```
=> account for prs without bodies

jenkins/codecov_response_metrics.py, jenkins/tests/test_codecov_analysis.py
This has a couple of changes to the codecov analysis script:
* rather than checking the diff between when the commit was pushed (which is an unreliable metric offered by the Github API), look at the diff between a triggering context (i.e. unit tests/travis) and codecov posting on the pull request
* add additional checking for corner cases (i.e. no need to check codecov if unit tests fail and therefore don't send coverage data)
* add tests
=> fix codecov script to look at other statuses and add tests

jenkins/edx_platform_test_notifier.py
Sometimes, a PR can have no commits. This can occur due to a reset/rebase. Here is an example: https://github.com/edx/edx-platform/pull/18758
I ran the code we use to get pull requests in the notifier script on the last 300 PRs into the edx-platform and this is the only scenario I could find that causes the following error:
```
Running test notifier script...
Traceback (most recent call last):
File "jenkins/edx_platform_test_notifier.py", line 160, in <module>
main()
File "<https://build.testeng.edx.org/job/edx-platform-test-notifier/ws/test_notifier_venv/local/lib/python2.7/site-packages/click/core.py",> line 722, in __call__
return self.main(*args, **kwargs)
File "<https://build.testeng.edx.org/job/edx-platform-test-notifier/ws/test_notifier_venv/local/lib/python2.7/site-packages/click/c …
```
=> handle prs with 0 commits in test notifier script

.travis.yml, jenkins/flow/pr/edx-platform-quality-pr.groovy
Add env var for target branch so that quality shard 4 can run xsscomitlinter against the proper target branch.
There seems to be something wrong with the envVarString, as I can only access the first variable when running the edx-platform scripts. I can continue to look into this separately.. or we can just move on in favor of pipelines since (I think) the tox env is just being set to null in all of our active jobs anyways. We'll of course need it to be functional in python3 jobs, but we're moving those over to pipelines this sprint anyways.
Also, Travis has been failing due to the following exception:
```
ImportError: No module named google_compute_engine
```
We've patched this in at least one other edx repo (edx/edx-analytics-pipeline#424) with export BOTO_CONFIG=/dev/null.
=> Add target branch to quality flow script

jenkins/bokchoy_db_pull_request.py, jenkins/edx_platform_test_notifier.py, jenkins/github_helpers.py, jenkins/tests/test_github_helpers.py, jenkins/tests/test_upgrade_python_requirements.py, jenkins/upgrade_python_requirements.py
* All changes for both the make upgrade job and the db cache job now exist in 1 commit.
* The refactor no longer allows creating missing files for the db cache job, I don't think this is a problem because they shouldn't really be creating new files. We can change this in the future if we want.
* Both jobs also auto close existing PR's before making a new one, since all we need is the latest PR.
=> Update auto PR scripts

scripts/create_incr_tickets.py, scripts/setup.sh, scripts/test.py
This is a helper script for analyzing a directory, and attempting to group sub directories containing a certain file type into small, fairly balanced batches. For now, it will dump a csv file listing each batch, describing how many python files are contained, which directories are contained, and if any of its sub-directories are present in other batches (meaning that they are blocked by the other).
There are some basic tests included. To run them, you need to first run `bash setup.sh` to set up the necessary directory structure for the tests. I opted for this instead of using pytest fixtures, just because this may be a 1-time script
My intention is to add jira integration, to create a templated INCR ticket for each test batch.
=> add script to generate incr tickets

scripts/create_incr_tickets.py
given an initial number for the next logical incr ticket to create, increment it and add it to the output csv for each batch to process
example output:
```
INCR-TICKET, BLOCKED, NUMBER OF PYTHON FILES, DIRECTORIES
INCR-232,False,9,../../edx-platform/lms/djangoapps/gating
INCR-233,False,14,../../edx-platform/lms/djangoapps/shoppingcart/management:../../edx-platform/lms/djangoapps/shoppingcart/tests
INCR-234,False,11,../../edx-platform/lms/djangoapps/shoppingcart/migrations:../../edx-platform/lms/djangoapps/shoppingcart/processors
INCR-235,True,12,../../edx-platform/lms/djangoapps/shoppingcart
INCR-236,False,9,../../edx-platform/lms/djangoapps/notes
INCR-237,False,5,../../edx-platform/lms/djangoapps/debug
INCR-238,False,15,../../edx-platform/lms/djangoapps/bulk_email/migrations:../../edx-pla …
```
=> add incr ticket numbers to output

jenkins/edx_platform_test_notifier.py
The notifier also needs to be able to comment on edx-platform-private. Right now, it's spamming edx-platform PRs incorrectly when triggered by private PR jobs.
=> Update notifier to handle repos outside of edx-platform

jenkins/github_helpers.py
I recently merged [a PR to stop upgrade jobs from mentioning the Master's squad](https://github.com/edx/jenkins-job-dsl/pull/1007). Since our rotating support engineer gets alerted of the PRs via OpsGenie, the mentions were just causing inbox noise.
That change [caused our upgrade jobs to start failing](https://build.testeng.edx.org/job/completion-upgrade-python-requirements/64/console):
```
06:00:27 INFO:root:Authenticating with Github
06:00:27 INFO:root:Trying to connect to repo: completion
06:00:28 INFO:root:modified files: ['requirements/dev.txt', 'requirements/doc.txt', 'requirements/quality.txt', 'requirements/test.txt', 'requirements/travis.txt']
06:00:30 INFO:root:Checking if there's any old pull requests to delete
06:00:30 INFO:root:Creating a new pull request
06:00:31 Traceback …
```
=> Handle absence of reviewers in calls to create_pull_request

jenkins/cleanup_python_code.py, jenkins/github_helpers.py, jenkins/pull_request_creator.py, jenkins/tests/test_upgrade_python_requirements.py, jenkins/upgrade_python_requirements.py
This is in service of ARCHBOM-1544 (automated code owner config PRs)
and needs to be merged before https://github.com/edx/jenkins-job-dsl-internal/pull/466
Breaking changes to PullRequestCreator:
- No longer accept a base SHA; this is now read from local repo
- Determine Github org and repo name from local repo's remotes:
- No longer accept org
- Don't assume folder name matches the github repo name
- Prevent possible behavior of matching repo in wrong org with
same name
Reliant scripts still accept sha and org options, but ignore them.
These can be cleaned up after the corresponding jenkins-job-dsl jobs and
scripts no longer pass these options.
Changes to GithubHelper:
- Add get_current_commit to get current SHA of local repo
- Add repo_from_remote to find repo on Github based on local …
=> Simplify PR creator, add CLI

jenkins/github_helpers.py
GitHub may tag additional, unasked-for reviewers on a PR if a CODEOWNERS
file is present. This change uses set comparison instead of list comparison
so that these extra reviewers can be ignored.
Also document some of the failure modes we've encountered.
=> Bugfix: Don't fail PR tagging check when additional reviewers present

LICENSE
Using [repo_health_dashboard](https://docs.google.com/spreadsheets/d/1VCxNVq-niT-uv5BFmsYPF21r6I2-IQ-GJbidF0zUPBc/edit#gid=921158295), we found that bunch of our public repositories did not have licenses.
It was determined all public repos should have a license. We did discovery on the repositories and determined which licenses were appropriate based on [confluence doc on licensing](https://openedx.atlassian.net/wiki/spaces/OPEN/pages/13959332/Licensing).
This PR adds the appropriate License.
You can find further info on this in the ticket [ARCHBOM-1618](https://openedx.atlassian.net/browse/ARCHBOM-1618)
=> [ARCHBOM-1618]: Adding agpl License to this public repository

jenkins/github_helpers.py, jenkins/pull_request_creator.py
Requirements-upgrade PRs were closing cleanup PRs; the former is run with
delete-old enabled, and the latter was not, but this missing check was
bypassing that control.
=> fix: Don't allow PR creation of one type to close PRs of another

jenkins/codecov_response_metrics.py, requirements/aws.txt, requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/testing.txt
A lot of automated CI jobs started failing today because of requirements conflict.
See 
https://build.testeng.edx.org/job/django-lang-pref-middleware-upgrade-python-requirements/49/ 
https://build.testeng.edx.org/job/edx-platform-test-notifier/189369/console
Turns out `pygithub` now requires `pyjwt<2.0` [Reference](https://github.com/PyGithub/PyGithub/releases/tag/v1.54.0)
=> fix: pygithub now requires pyjwt<2.0

jenkins/github_helpers.py
Sometimes the upgrade_requirements job fails with a 404 trying to
retrieve the list of requested reviewers.  Put in a pause to try to
avoid that problem.
An example of a failing build:
https://github.com/edx/openedxstats/runs/3605917319
```
INFO:root:Tagging reviewers: users=NotSet and teams=['community-engineering']
Traceback (most recent call last):
File "/home/runner/work/openedxstats/openedxstats/testeng-ci/jenkins/github_helpers.py", line 196, in create_pull_request
self.verify_reviewers_tagged(pull_request, user_reviewers, team_reviewers)
File "/home/runner/work/openedxstats/openedxstats/testeng-ci/jenkins/github_helpers.py", line 219, in verify_reviewers_tagged
tagged_users = [user.login for user in tagged_for_review[0]]
File …
```
=> fix: wait a moment before asking about the pull request

jenkins/pull_request_creator.py, jenkins/tests/test_upgrade_python_requirements.py
Adds an option `--output-pr-url-for-github-action` to the `pull_request_creator` script which causes the resulting PR URL to be put in a github-parseable output tag, for use downstream in a github action workflow.
To use the new output param, set an `id` on the step from which the `pull_request_creator` is invoked, like https://github.com/edx/edx-proctoring/blob/5d025d4c78142e0da518ca49a761837e8d080831/.github/workflows/upgrade-python-requirements.yml#L47. Then in subsequent steps of the same workflow you can get the output PR using the expression `${{ steps.<whatever id you chose>.outputs.generated_pr }}`. Note that the param will only be set if a new PR is created; if no changes are needed or a branch with the needed changes already exists, then the script will succeed but not output …
=> feat: wrap PR link in github action output syntax

jenkins/github_helpers.py
Switching to '--exclude-standard' option to use standard git exclusions for untracked files while creating PRs. 
For reference see [docs](https://git-scm.com/docs/git-ls-files)
Previously we were using `--exclude-from=.gitignore` which ignores only the files added in .gitignore but sometimes we want to ignore some file without updating .gitignore. Standard approach for this is to update '.git/info/exclude' file locally but that doesn't work with the `--exclude-from` thing. Using `--exclude-standard`, we can achieve the standard behaviour.
=> fix: Use standard git exclusions in PR creation

jenkins/pull_request_creator.py
The flag was added for `Bulk repo update`. It had been set to True by default but that is messing up with the requirements upgrade job. `Bulk repo update` job's interface provides us the option to set the flag to true or false depending upon our usage and hence this should be False by default so that it doesn't cause issue with other jobs.
=> Set force delete param to False by default

.gitignore, jenkins/pull_request_creator.py, jenkins/tests/test_upgrade_python_requirements.py
This PR fixes the delete branch functionality for existing branches. If a branch exists already but it isn't linked to any open PR then the script doesn't cater deleting that branch.
Team noted this bug during the schedules upgrade Requirement Job failures where the job was failing if a branch with same `SHA` existed. Notably we are appending the commit SHA of the last commit on master branch and if the commit is same between different job runs we run into this issue where the job fails. 
The `existing branch check` was bypassed due to the `force delete flag` which has been fixed in this PR:https://github.com/edx/testeng-ci/pull/322
Previously, for repos where there is seldom a new commit, the job would keep passing without making any upgrade PR and just log `Branch for this SHA` already …
=> Fix delete branch functionality

requirements/base.in, requirements/base.txt, requirements/testing.txt
With the recent change pull request creator script, we are now comparing the version of packages during the upgrade python requirements script. We are using this package but not mentioned in the base.in due to which this script was failing for the Bulk Repo Update job.
=> chore: mention `packaging` as explicit dependency

jenkins/github_helpers.py, jenkins/tests/test_data/diff.txt
Skip, if the package location is changed in the txt file only and both versions are the same.
=> fix: improve upgrade automation script

jenkins/github_helpers.py
Previously, it was failing when the file was deleted on fetching the file content. So updated the code to now remove file from git tree if the path doesn't exist.
=> fix: remove file from git tree when delete
