openedx/testeng-ci

- jenkins/deduper.py
- jenkins/tests/test_deduper.py
> Fix one-per-author argument definition

- aws/get_running_instances.py
- aws/tests/test_get_running_instances.py
- jenkins/build.py
- jenkins/deduper.py
- jenkins/job.py
- jenkins/tests/test_workers.py
- jenkins/timeout.py
- jenkins/workers.py
@jzoldak @benpatterson  Please review....
This is adding more details about number of workers based on tags, and formatting the output according to splunk best practices.
> refactor logging and add more worker data

- jenkins/flow/master/edx-platform-lettuce-master.groovy
lettuce only. FYI @jzoldak @clytwynec
> Url should be adaptable to Jenkins instance.

- .travis.yml
> Use the travis container based infrastructure

- jenkins/freestyle/get-sitespeed-report.sh
> Add a browser choice option for sitespeed builds

- jenkins/freestyle/get-sitespeed-report.sh
- jenkins/freestyle/lms-budget.json
- jenkins/freestyle/sitespeed-lms-urls.txt
@benpatterson I wanted to give you a heads up on this one.
Let's discuss offline where we think we should keep the budget file and the URLs that we will be running the regression tests against.
> Add ability to test multiple URLs for regression purposes

- jenkins/freestyle/lms-budget-regression.json
> Set budget for perf page.

- jenkins/freestyle/get-sitespeed-report.sh
> Redact debug statement.

- jenkins/freestyle/get-sitespeed-report.sh
> Statement should handle when var is not set

- jenkins/freestyle/github-build-status.groovy
@benpatterson 
Oh, and here's the groovy script too. Also not used programmatically by the job, but putting it here so that  it is under source control.
> Add the groovy script that parses the output and adds icons

- jenkins/freestyle/get-sitespeed-report.sh
@benpatterson this will fix the "unary operator expected" error on the sitespeed job.
> Switch to double bracket operator in bash script

- mobile_app/README.md
- mobile_app/checkout_build_repos.py
- mobile_app/path_constants.py
- mobile_app/test/test_checkout_build_repos.py
- mobile_app/test/test_trigger_build.py
- mobile_app/test/utils.py
- mobile_app/trigger_build.py
JIRA: https://openedx.atlassian.net/browse/MA-1514
> Script to pull repos based on config.

- mobile_app/README.md
- mobile_app/make_android_build.py
- mobile_app/make_build.py
- mobile_app/make_ios_build.py
- mobile_app/test/test_make_build.py
Adds two new scripts ``make_ios_build`` and ``make_android_build`` which
are shortcuts for building the respective apps
> Add app specific builders

- mobile_app/make_android_build.py
- mobile_app/make_build.py
- mobile_app/make_ios_build.py
- mobile_app/test/test_ios_build.py
- mobile_app/test/test_make_build.py
- mobile_app/test/test_utils.py
- mobile_app/trigger_build.py
- mobile_app/upload_build.py
- mobile_app/utils.py
JIRA: https://openedx.atlassian.net/browse/MA-2044
> Support uploading to test flight

- jenkins/flow/master/edx-platform-python-unittests-master.groovy
- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
> Create a 4th lms unit shard.

- release/get_token.py
- release/tests/test_get_token.py
@jzoldak @benpatterson @cpennington rebranched and pushed to follow proper workflow (and include wording fixes in docstrings)
> Re-committing with docstrings fixes, on a new branch

- jenkins/build.py
- jenkins/deduper.py
- jenkins/job.py
@jzoldak @estute 
I had some extra cycles with a low internet connection so did some pylint fixes. This gets through about 1/3 of the ones in the jenkins/ directory. PTAL.
> Pylint fixes for jenkins.build, .job, and .deduper

- jenkins/flow/pr/edx-platform-lettuce-pr.groovy
@estute @jzoldak @benpatterson 
Sharding Script for the Lettuce PR. Same updates as the rest of the sharding scripts: being able to specify the subset job used and directory. Whenever you have a chance to look it over would be great :)
> Update Lettuce Shard Script

- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
@jzoldak @estute 
Python Pr Sharding Script. Includes defaults so everything is compatible :)
> Python Sharding Script

- jenkins/flow/master/edx-platform-python-unittests-master.groovy
@estute @jzoldak 
Refactored Python Master to use the correct unit coverage job
> Fix Python Master Job

- jenkins/flow/master/edx-platform-bok-choy-master.groovy
- jenkins/flow/master/edx-platform-python-unittests-master.groovy
@estute @jzoldak 
This goes along with https://github.com/edx/jenkins-job-dsl/pull/43. I had apparently changed the lettuce master flow script which is why it doesn't appear here.
> Refactor to post status to github

- release/create_candidate_pr.py
- release/get_token.py
- release/github_api.py
- release/tests/test_github_api.py
- release/tests/test_utils.py
@jzoldak @nasthagiri PTAL. These updates fix the script errors from earlier today as well as add an option to specify the SHA with which to create the PR.
> Fix delete and add SHA override

- jenkins/flow/master/edx-platform-bok-choy-master.groovy
- jenkins/flow/master/edx-platform-lettuce-master.groovy
- jenkins/flow/master/edx-platform-python-unittests-master.groovy
- jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
- jenkins/flow/pr/edx-platform-lettuce-pr.groovy
- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
@benpatterson 
stage 2:
hook testeng-ci into the subset jobs worker label param (still no affect on current jobs due to default values)
> pass worker types via dsl to subset jobs

- lambdas/webhook_forwarder/README.md
- lambdas/webhook_forwarder/webhook_forwarder.py
> add webhook forwarder and README

- jenkins/freestyle/delete-old-workers.groovy
@edx/testeng @cpennington 
Also this one, after working through it with Cale.
> Only delete workers that are not doing anything.

- jenkins/freestyle/disable-old-workers.groovy
> Add disable old workers script.

- .gitignore
- .travis.yml
- lambdas/webhook_forwarder/webhook_forwarder.py
- lambdas/webhook_processor/README.md
- lambdas/webhook_processor/test/test_webhook_processor.py
- lambdas/webhook_processor/webhook_processor.py
This is the lambda code that will read github webhooks off the kinesis stream and forward them to a list of URLs (jenkins webhook endpoints).
@estute @michaelyoungstrom pls review.
FYI @benpatterson
> webhook processor  TE-2069

- lambdas/webhook_processor/README.md
- lambdas/webhook_processor/test/test_webhook_processor.py
- lambdas/webhook_processor/webhook_processor.py
> Switch webhook processor lambda to send json payloads

- jenkins/flow/master/edx-platform-bok-choy-master.groovy
- jenkins/flow/master/edx-platform-lettuce-master.groovy
- jenkins/flow/master/edx-platform-python-unittests-master.groovy
- jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
- jenkins/flow/pr/edx-platform-lettuce-pr.groovy
This repeats the same change that @estute made for the python-pr job.
See #111.
> Do not archive raw artifacts copied up from subset jobs

- jenkins/bokchoy_db_pull_request.py
Call .format correctly in logging statement.
> Fix logging statement

- jenkins/toggle-spigot.py
We were hitting a race condition when changing the state of the spigot that resulted in losing a significant amount of webhook data.
Changing the spigot state consists of 2 parts: changing the API stage variable, and enabling/disabling the cloudwatch event trigger that controls the `send_from_queue` lambda function. The issue is that there seems to be a delay when setting the API stage variable. When going from `OFF` to `ON`, the cloudwatch event ends up being turned on before the stage variable gets flipped, which means hooks start to dequeue while the `process_webhooks` lambda function still "thinks" hooks should be queued. It therefore doesn't transmit the hooks to Jenkins and throws an error. Due to a bug in the error reporting from that lambda and our API Gateway, the …
> Prevent race condition in toggle-spigot function

- jenkins/flow/master/edx-platform-bok-choy-master.groovy
- jenkins/flow/master/edx-platform-lettuce-master.groovy
- jenkins/flow/master/edx-platform-python-unittests-master.groovy
- jenkins/flow/master/edx-platform-quality-master.groovy
- jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
- jenkins/flow/pr/edx-platform-lettuce-pr.groovy
- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
- jenkins/flow/pr/edx-platform-quality-pr.groovy
> Revert "Refactor flow jobs to not clone platform"

- jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
- jenkins/flow/pr/edx-platform-lettuce-pr.groovy
- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
- jenkins/flow/pr/edx-platform-quality-pr.groovy
> PR jobs shouldnt clone edx-platform

- jenkins/flow/master/edx-platform-python-unittests-master.groovy
- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
Part of TE-2427:
* increase the number of lms, cms, and commonlib shards for python pr tests
> shard commonlib unit tests

- jenkins/edx_platform_test_notifier.py
This will add which contexts failed, if any, to the message sent by the notifier script after platform prs are run.
> notifier alerts which contexts failed

- jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
- jenkins/flow/pr/edx-platform-lettuce-pr.groovy
- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
- jenkins/flow/pr/edx-platform-quality-pr.groovy
> Revert "use toxEnv instead of djangoVersion"

- jenkins/flow/pr/edx-platform-bok-choy-pr.groovy
- jenkins/flow/pr/edx-platform-lettuce-pr.groovy
- jenkins/flow/pr/edx-platform-python-unittests-pr.groovy
- jenkins/flow/pr/edx-platform-quality-pr.groovy
Once I merge in https://github.com/edx/edx-platform/pull/18381, I can re-revert his PR.
> fix tox env default value

- jenkins/codecov_response_metrics.py
I am not sure about the very end of this- I guess it depends on what we want to do. Do we want to be alerted once a certain condition has been met (i.e. a certain threshold has been exceeded) or just dump all of this data into splunk to create a graph? Open to opinions
> add script to measure codecov response metrics

- jenkins/codecov_response_metrics.py
fix for https://build.testeng.edx.org/job/gather-codecov-metrics/312/console
> handle encoding issues in pr title

- jenkins/bokchoy_db_pull_request.py
- jenkins/github_helpers.py
- jenkins/tests/test_bokchoy_db_pull_request.py
- jenkins/tests/test_upgrade_python_requirements.py
- jenkins/upgrade_python_requirements.py
Clean up by deleting branches for old PR's when we close them
> Delete branch on old PR's

- jenkins/upgrade_python_requirements.py
Update the description for `make upgrade` PRs to include a link to the Confluence page listing changelogs for packages used somewhere in Open edX.  Also fixed all current pylint warnings in the module.
> Add link to changelogs wiki page in upgrade PRs

- jenkins/github_helpers.py
- jenkins/repo_health_reports.py
For the Repo Health Dashboard project, we want to store repo health reports in https://github.com/edx/repo-tools-data. This python script is necessary to create a PR to store the  report.
The added file is a copy of this: https://github.com/edx/testeng-ci/blob/master/jenkins/upgrade_python_requirements.py
The script is meant to be used in this PR: https://github.com/edx/jenkins-job-dsl/pull/927
> Adding python script to create github PR

- jenkins/bokchoy_db_pull_request.py
- lambdas/process_webhooks/process_webhooks.py
- lambdas/process_webhooks/test/test_process_webhooks.py
- lambdas/restart_jenkins/restart_jenkins.py
- lambdas/send_from_queue/send_from_queue.py
- lambdas/send_from_queue/test/test_send_from_queue.py
- travis/build_info.py
The testeng GitHub team now only has 2 former members; have arch-bom review these PRs instead as the owner of the edx-platform testing framework.
Also fixed some lint checks and tests that were failing on master due to previous dependency upgrades.
> Have arch-bom review bok-choy DB cache update PRs

- jenkins/bokchoy_db_pull_request.py
Switch the team receiving notifications of these automated PRs from arch-bom to arbi-bom.
> Notify arbi-bom of DB cache update PRs

- jenkins/github_helpers.py
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1950
> BOM-1950 : Verify that "make upgrade" jobs notify correct reviewers

- jenkins/github_helpers.py
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1987)
> Skip PR reviewer verification for cleanup PRs

- requirements/aws.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/testing.txt
- requirements/travis.txt
Make Upgrade Job Was Failing On Jenkins, Fixed it manually.
> BOM-2056 : Make upgrade fix

- requirements/aws.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/testing.txt
- requirements/travis.txt
Reverting to fix failures triggered by the changes.  Example: https://build.testeng.edx.org/job/edx-platform-test-notifier/165227/
Reverts edx/testeng-ci#238
> Revert "BOM-2056 : Make upgrade fix"

- .travis.yml
- requirements/aws.txt
- requirements/base.txt
- requirements/dev.txt
- requirements/testing.txt
- requirements/travis.txt
- tox.ini
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2070
> BOM-2070 : Add Python 3.8 Support

- jenkins/github_helpers.py
- jenkins/pull_request_creator.py
- jenkins/tests/test_github_helpers.py
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1770
Related Changes in jenkins-job dsl : https://github.com/edx/jenkins-job-dsl/pull/1189
> BOM-1770 : Add branch parameter to make-upgrade

- jenkins/github_helpers.py
We've had a number of issues with tagging not working as expected.
> Add logging for reviewer tagging

- jenkins/github_helpers.py
this step is failing. We need some traceback to do debugging.
> build: create-pull request is failing. exposing traceback.

- jenkins/github_helpers.py
- jenkins/tests/test_upgrade_python_requirements.py
Its a discovery ticket to do a `automerge` for upgrade prs. 
It will get the diff-url of pr and pick the changes using regex and then compare packages.
This will run only on repo-health-dashboard prs.
> build: parsing packages.

- jenkins/github_helpers.py
> Revert "build: Adding functionality to parse upgrade requirements packages."

- jenkins/github_helpers.py
- jenkins/tests/test_upgrade_python_requirements.py
> Revert "build: parsing packages."

- jenkins/github_helpers.py
- jenkins/tests/test_upgrade_python_requirements.py
Its a discovery ticket to do a automerge for upgrade prs.
It will get the diff-url of pr and pick the changes using regex and then compare packages.
This will run only on repo-health-dashboard prs.
> Comparing package

- jenkins/github_helpers.py
This is discovery task, so adding few repos. This solution only works for public repos.
> build: Adding more public repos.

- jenkins/pull_request_creator.py
This PR fixes the delete old branch functionality of pull request creator script. For more details: https://github.com/edx/testeng-ci/pull/324#discussion_r1025020071
> Fix delete old branch functionality

- jenkins/github_helpers.py
- jenkins/tests/test_upgrade_python_requirements.py
Using this way we can access the private repos for diff changes.
> Accessing pvt repos

- jenkins/github_helpers.py
- jenkins/tests/test_upgrade_python_requirements.py
Now all repos will parse.
Check the major version comparison also.
> chore: Checking upgrade packages.

- jenkins/github_helpers.py
- jenkins/tests/test_upgrade_python_requirements.py
Updating msg for clarity in case of any version downgrade or major upgrade.
> chore: fixing message for clarity.

- jenkins/github_helpers.py
- jenkins/tests/test_upgrade_python_requirements.py
Improve regex
Adding packages info on PR as comments
> Fixing errors

- jenkins/github_helpers.py
chore: Adding updated packages info
> fix: Improved regex and capture more missing scenarios.

- jenkins/github_helpers.py
We dont want to merge each PR with label.
Only those which are under arch-bom ownership.
> temp: Removing lebeling to avoid mering prs across organization wise.
